workflows:
  mapbox-navigation-example:
    name: Mapbox Navigation Example Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.3
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          # We need to set this in the example's android folder
          echo "flutter.sdk=$FLUTTER_ROOT" > example/android/local.properties

      - name: Get dependencies for Root and Example
        script: |
          # First, get dependencies for the plugin itself
          flutter pub get
          
          # Then, go into the example folder and get dependencies there
          cd example
          flutter pub get

      - name: Build Android APK (Student)
        script: |
          cd example
          flutter build apk -t lib/main_student.dart --release --no-tree-shake-icons --android-skip-build-dependency-validation
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/student-app.apk

      - name: Build Android APK (Driver)
        script: |
          cd example
          flutter build apk -t lib/main_driver.dart --release --no-tree-shake-icons --android-skip-build-dependency-validation
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/driver-app.apk

      - name: Build Windows App (Admin)
        script: |
          cd example
          flutter build windows -t lib/main_admin.dart --release

    artifacts:
      - example/build/app/outputs/flutter-apk/student-app.apk
      - example/build/app/outputs/flutter-apk/driver-app.apk
      - example/build/windows/runner/Release/*.exe
